// Generates a Word-compatible .doc file from UAR form data
// Uses HTML with Word XML namespaces — no npm dependencies needed

export function generateUARDocument(formData) {
  const html = `
<html xmlns:o="urn:schemas-microsoft-com:office:office"
      xmlns:w="urn:schemas-microsoft-com:office:word"
      xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta charset="utf-8">
<style>
  body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; margin: 1in; color: #1a1a1a; }
  h1 { font-size: 18pt; color: #1e3a5f; border-bottom: 2px solid #1e3a5f; padding-bottom: 8px; margin-bottom: 16px; }
  h2 { font-size: 13pt; color: #1e3a5f; margin-top: 20px; margin-bottom: 8px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
  table { border-collapse: collapse; width: 100%; margin-bottom: 12px; }
  td { padding: 6px 10px; border: 1px solid #ccc; vertical-align: top; font-size: 10pt; }
  td:first-child { background: #f5f7fa; font-weight: bold; width: 200px; color: #333; }
  .severity-critical { color: #dc2626; font-weight: bold; }
  .severity-high { color: #ea580c; font-weight: bold; }
  .severity-medium { color: #d97706; font-weight: bold; }
  .severity-low { color: #2563eb; }
  .section-note { font-size: 9pt; color: #666; font-style: italic; margin-bottom: 8px; }
  .narrative { background: #fafafa; border: 1px solid #ddd; padding: 12px; margin-top: 8px; white-space: pre-wrap; font-size: 10pt; line-height: 1.5; }
  .footer { margin-top: 24px; font-size: 9pt; color: #888; border-top: 1px solid #ddd; padding-top: 8px; }
</style>
</head>
<body>
<h1>Questionable Activity Referral (QAR) Form</h1>

<h2>QAR Details</h2>
<table>
  <tr><td>Merchant Name</td><td>${esc(formData.merchantName)}</td></tr>
  <tr><td>Referral Date</td><td>${esc(formData.referralDate)}</td></tr>
  <tr><td>Partner Platform</td><td>${esc(formData.partnerName)}</td></tr>
  <tr><td>Product</td><td>${esc(formData.useCase)}</td></tr>
  <tr><td>Completed By</td><td>${esc(formData.completedBy)}</td></tr>
  <tr><td>Contact Email</td><td>${esc(formData.contactEmail)}</td></tr>
</table>

<h2>Business Details</h2>
<table>
  <tr><td>Customer ID</td><td>${esc(formData.merchantId)}</td></tr>
  <tr><td>Account ID</td><td>${esc(formData.accountId)}</td></tr>
  <tr><td>Business Name</td><td>${esc(formData.merchantName)}</td></tr>
  <tr><td>Business Address</td><td>${esc(formData.businessAddress)}</td></tr>
  <tr><td>Business EIN</td><td>${esc(formData.ein)}</td></tr>
</table>

<h2>Beneficial Owner(s) Details</h2>
<p class="section-note">To be completed manually by compliance analyst</p>
<table>
  <tr><td>Beneficial Owner Name</td><td>${esc(formData.beneficialOwnerName)}</td></tr>
  <tr><td>Beneficial Owner Address</td><td>${esc(formData.beneficialOwnerAddress)}</td></tr>
  <tr><td>Beneficial Owner DOB</td><td>${esc(formData.beneficialOwnerDOB)}</td></tr>
  <tr><td>Beneficial Owner SSN</td><td>${esc(formData.beneficialOwnerSSN)}</td></tr>
  <tr><td>Phone Number</td><td>${esc(formData.phone)}</td></tr>
  <tr><td>Email Address</td><td>${esc(formData.email)}</td></tr>
</table>

<h2>Details of Questionable Activity / Transaction</h2>
<table>
  <tr><td>Date or Date Range</td><td>${esc(formData.activityDateRange)}</td></tr>
  <tr><td>Date of Detection</td><td>${esc(formData.detectionDate)}</td></tr>
  <tr><td>Dollar Amount</td><td>${esc(formData.dollarAmount)}</td></tr>
  <tr><td>Transaction ID</td><td>${esc(formData.transactionId)}</td></tr>
  <tr><td>Decision ID</td><td>${esc(formData.decisionId)}</td></tr>
  <tr><td>Severity Level</td><td class="severity-${formData.severity?.toLowerCase()}">${esc(formData.severity)}</td></tr>
  <tr><td>Network</td><td>${esc(formData.network)}</td></tr>
  <tr><td>Triggered Conditions</td><td>${esc(formData.triggeredConditions)}</td></tr>
  <tr><td>Velocity Risk Score</td><td>${esc(String(formData.velocityRiskScore))}</td></tr>
  <tr><td>Description</td><td>${esc(formData.description)}</td></tr>
</table>

<h2>Questionable Activity Summary</h2>
<div class="narrative">${esc(formData.narrative)}</div>

<div class="footer">
  <p>Generated by Jaris FinOps Dashboard | ${esc(formData.referralDate)} | Decision ID: ${esc(formData.decisionId)}</p>
  <p>This document is confidential and intended for regulatory compliance purposes only.</p>
</div>
</body>
</html>`;

  const blob = new Blob([html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  const safeName = (formData.merchantName || 'Unknown').replace(/[^a-zA-Z0-9]/g, '_');
  const dateStr = new Date().toISOString().slice(0, 10);
  a.href = url;
  a.download = `QAR_Referral_${safeName}_${dateStr}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function esc(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
